version: "3.7"
services:
    db:
        build: ./db
        container_name: db
        ports:
            - "3306:3306"
        volumes: 
            - data:/var/lib/mysql
        env_file: 
            - env/db.env
        networks:
            website_network:
                aliases: 
                    - wordpress
    wordpress:
        build: ./wordpress
        container_name: wordpress
        ports:
            - "80"
        networks:
            website_network:
                aliases: 
                    - wordpress
        env_file: 
            - env/wordpress.env
        volumes:
            - wordpress:/var/www/html
    nuxt:
        build: ./nuxt
        container_name: nuxt
        ports: 
            - "3000"
        networks: 
            website_network:
                aliases: 
                    - nuxt
    nginx:
        build: ./nginx
        container_name: nginx
        depends_on: ["nuxt"]
        ports:
            - "443:443"
            - "80"
        networks:
            website_network:
                aliases: 
                    - nginx-proxy
    cloudflare:
        build: ./cloudflare
        container_name: cloudflare
        restart: always
        env_file: 
            - env/cloudflare.env
networks: 
    website_network:
        name: website_network
volumes: 
    data:
        driver: local
        name: data
    wordpress: